# Generated by Django 4.2.24 on 2025-09-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arsip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Arsip')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('tanggal', models.DateField(verbose_name='Tanggal Arsip')),
            ],
            options={
                'verbose_name': 'Arsip',
                'verbose_name_plural': 'Arsip',
            },
        ),
    ]
